architect:
- dmzaytsev
- yegor256
- karato
assets:
  settings.xml: yegor256/home#assets/netbout/settings.xml
  settings-snapshot.xml: yegor256/home#assets/netbout/settings-snapshot.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
  id_rsa: yegor256/home#assets/heroku-key
  id_rsa.pub: yegor256/home#assets/heroku-key.pub
  s3cfg: yegor256/home#assets/s3cfg
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
install: |
  sudo locale-gen en_US en_US.UTF-8
  sudo dpkg-reconfigure locales
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
  sudo gem install --no-ri --no-rdoc pdd
  sudo gem install --no-ri --no-rdoc est
  mkdir ~/.ssh
  mv ../id_rsa ../id_rsa.pub ~/.ssh
  chmod -R 600 ~/.ssh/*
  echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
deploy:
  script: |
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
    git remote add heroku git@heroku.com:netbout-snapshot.git
    cp ../settings-snapshot.xml settings.xml
    git add settings.xml
    git commit -m 'settings.xml'
    git push -f heroku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    mvn clean
    pdd  --file=netbout.xml
    s3cmd --no-progress put netbout.xml --config=../s3cfg s3://pdd.teamed.io/netbout.xml
    est --dir=./est --verbose --file=netbout.xml --format=xml
    s3cmd --no-progress put netbout.xml --config=../s3cfg s3://est.teamed.io/netbout.xml
merge:
  script: |
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean
    pdd  --file=/dev/null
    est --dir=est --file=/dev/null
    ./years.sh
  commanders:
  - carlosmiranda
  - darkled
  - dmzaytsev
  - essobedo
  - ggajos
  - hdouss
  - krzyk
  - longtimeago
  - mkordas
  - original-brownbear
  - pinaf
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Psonatype -Pnetbout --errors --batch-mode --settings ../settings.xml
    git remote add heroku git@heroku.com:netbout.git
    build=$(git rev-parse --short HEAD)
    sed -i "s/BUILD/${build}/g" netbout-web/src/main/resources/META-INF/MANIFEST.MF
    sed -i "s/BUILD/${build}/g" netbout-web/src/main/resources/log4j.properties
    git add netbout-web/src/main/resources/META-INF/MANIFEST.MF
    git add netbout-web/src/main/resources/log4j.properties
    git commit -m 'build number set'
    cp ../settings.xml settings.xml
    git add settings.xml
    git commit -m 'settings.xml'
    git push -f heroku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://www.netbout.com
    mvn clean install site-deploy -Psite --errors --settings ../settings.xml --batch-mode
  commanders:
  - dmzaytsev
  - yegor256