language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
addons:
  apt:
    packages:
    - libmagic1
    - libmagic-dev
before_install:
  - unset GEM_PATH
  - rvm install 2.6.0
  - rvm use 2.6.0
install:
  - npm install phantomjs -g
  - npm install casperjs -g
  - gem install pdd -v 0.20.5
  - gem install est -v 0.3.4
script:
  - mvn clean install -Pqulice coveralls:report --batch-mode --errors
  - mvn clean
  - pdd  --file=/dev/null
  - est --dir=est --file=/dev/null
  - ./years.sh
jdk:
  - openjdk8
